batch_size: 35
height: 96
learning_rate: 0.001
max_text_length: 73
model_path: Models/202304010616
train_epochs: 200
train_workers: 35
vocab: '''3.FR20JWIe8CyBowxTV5rgOYQ,ipPcqDGnMAK(Eb6)fH:"9LlUt;jsz m4&1#kZ-adNhvu7!S?'
width: 1408
